### ISSUE TITLE
Read over two documents and make corrections

### ISSUE THREAD

**Issue by istx25** [linehop/guides#3]
1. https://github.com/linehop/guides/blob/master/Guides/miscellaneous.md
2. https://github.com/linehop/guides/blob/master/README.md

**Comment by zspell** [comment]
Max can you take care of this I have class all day and then will be traveling to Charlotte. Thanks. If not I'll read it tomorrow. 

---

Zach Spellman
University of Michigan, 2016
(847) 513-4778

**Comment by istx25** [comment]
No, no. I assigned this to @damonjones. Just grammar checks/etc.

**Comment by istx25** [comment]
I will need to go over these with you, but this specific issue was about the grammar. :smiley:

**Comment by zspell** [comment]
Sweet no worries 

---

Zach Spellman
University of Michigan, 2016
(847) 513-4778

**Comment by damonjones** [comment]
All good, from my perspective.
